Bounds = {
    MAX_X: 1700,
    MAX_Y: 900
}
FRAME_RATE = 100

MAX_SPEED = 20
MAX_SIMULATION_SPEED = 15
POP_SIZE = 100
WALL_WIDTH = 70
SENSOR_DISTANCE = Bounds.MAX_X / (WALL_WIDTH / 4)
NOISE = 1.5
MAX_FUEL = 15 * NOISE
MINIMUM_PERCENT = 20
DRAW_RAYS = false
DRAW_GREEN_WALLS = false

useSaved = false
